SQLalchemy_Att_MVC_/models/user_model.py
from database import db
from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy import Integer, Text, Boolean
from flask_login import UserMixin

class Usuario(db.Model, UserMixin):
    __tablename__  = "usuarios"

    id: Mapped[int] = mapped_column("id", Integer, primary_key = True, autoincrement=True)

    email: Mapped[str] = mapped_column("email", Text, nullable=False, unique=True)

    senha: Mapped[str] = mapped_column("senha", Text, nullable=False)

    def __init__(self, email, senha):
        self.email = email        
        self.senha = senha         

    @staticmethod
    def get_email(email):
        print(f"Buscando usuário com email:{email}")
        return db.session.query(Usuario).filter_by(email=email).first()
    
    @staticmethod 
    def create(email, senha):
        new_user = Usuario(email=email,senha=senha)
        db.session.add(new_user)
        db.session.commit()

    @staticmethod 
    def modify(email,id):
        user = db.session.query(Usuario).filter(Usuario.id == id).first()  
        user.email = email
        db.session.add(user)
        db.session.commit()
     
    @staticmethod
    def delete_user(id):
        user = db.session.query(Usuario).filter(Usuario.id == id).first()
        if user is None:
          raise ValueError("Usuário não encontrado.")
        db.session.delete(user)
        db.session.commit()

SQLalchemy_Att_MVC_/app.py
from flask import Flask 
from flask_login import LoginManager
from database import init_db 
from controllers.user import user_bp 
from models.user_model import Usuario


app = Flask(__name__)
app.config['SECRET_KEY'] =  "SENHA"

login_manager = LoginManager()
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(int(user_id))

init_db(app)

app.register_blueprint(user_bp)

if __name__ == "__main__":
    app.run(debug=True)
            

SQLalchemy_Att_MVC_/controllers/user.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, session, make_response

from flask_login import login_user, login_required, logout_user, current_user

from werkzeug.security import generate_password_hash, check_password_hash

from models.user_model import Usuario

from database import db 

user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def index():
    users = Usuario.query.all()
    return render_template('index.html', users=users)

@user_bp.route('/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':

        email = request.form['email']
        senha = request.form['password']

        senha_hashed = generate_password_hash(senha)

        Usuario.create(email, senha_hashed)

        flash("Usuário registrado com sucesso!", 'success')
        user = Usuario.get_email(email)
        login_user(user)
        return redirect(url_for('user.index'))

    return render_template('create.html')

@user_bp.route('/<int:id>/edit', methods=['POST', 'GET'])
def edit(id):
    user = db.session.query(Usuario).filter(Usuario.id == id).first()
    
    if user is None:
        return redirect(url_for('error', message='Usuário Inexistente'))
    
    if request.method == 'POST':
        new_email = request.form['email']
        
        # Chama o método modify (controllers) para atualizar o email
        Usuario.modify(new_email, id)
        
        return redirect(url_for('user.index'))
    
    return render_template('edit.html', user=user)

@user_bp.route('/<int:id>/delete', methods=['POST', 'GET'])
def delete(id):
    user = db.session.query(Usuario).filter(Usuario.id == id).first()
    
    if user is None:
        return redirect(url_for('error', message='Usuário Inexistente'))
    
    if request.method == 'POST':
        try:
            Usuario.delete_user(id)
            return redirect(url_for('user.index'))
        except Exception as e:
            return redirect(url_for('error', message='Erro ao deletar usuário.'))
    
    return render_template('delete.html', user=user)

SQLalchemy_Att_MVC_/database/__init__.py
from flask_sqlalchemy import SQLAlchemy # type: ignore

db = SQLAlchemy()

def init_db(app):
    app.config['SECRET_KEY'] = "superdificil2"
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///banco.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)

    with app.app_context():
        db.create_all()

SQLalchemy_Att_MVC_/templates/create.html
{% extends 'layout.html' %}

{% block conteudo %}

<div class="users">

    <form action="{{url_for('user.create')}}" method="post">
        <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
          
        <input type="password" name="password" placeholder="Senha">
        <button>Enviar</button>
    </form>

</div>
    
{% endblock %}

SQLalchemy_Att_MVC_/templates/delete.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="users">

    <form action="{{url_for('user.delete', id=user['id'])}}" method="post">
        <input type="email" name="email" placeholder="Email" value="{{user['email']}}">
        <button>Enviar</button>
    </form>

</div>
{% endblock %}

SQLalchemy_Att_MVC_/templates/edit.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="users">

    <form action="{{url_for('user.edit', id=user['id'])}}" method="post">
        <input type="email" name="email" placeholder="Email" value="{{user['email']}}">
        <button>Enviar</button>
    </form>

</div>
{% endblock %}

SQLalchemy_Att_MVC_/templates/index.html
{% extends 'layout.html' %}

{% block link %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{% endblock %}

{% block conteudo %}

<div class="users">
    <ul>
        {% for user in users %}
        <li>
            <span>Email:</span> 
            {{user['email']}} 
            <a href="{{url_for('user.edit', id=user['id'])}}">
                <span class="material-symbols-outlined">edit_document</span>
            </a> 
          
            <a href="{{url_for('user.delete', id=user['id'])}}">
                <span class="material-symbols-outlined">delete</span>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

SQLalchemy_Att_MVC_/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQLITE 3</title>

    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">


    {% block link %}
        
    {% endblock %}

</head>
<body>

    <div class="container">
        <div class="nav">
            <h2><a href="{{url_for('user.index')}}">Users</a></h2>
            <h2><a href="{{url_for('user.create')}}">Add</a> </h2>
        </div>
        <div class="main">
            {% block conteudo %}
                
            {% endblock %}
        </div>
    </div>
    
    
</body>
</html>