flask_alchemy(Att-MVC)/models/book_model.py
from database import db
from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy import Text 

class Book(db.Model):
    __tablename__ = 'books'
    id:Mapped[int] = mapped_column(primary_key=True)
    titulo:Mapped[str] = mapped_column("titulo", Text, nullable=False )
    autor:Mapped[str]= mapped_column("autor", Text, nullable=False )

    def __init__(self, titulo, autor):
        self.titulo = titulo
        self.autor = autor 

    def create_book(titulo, autor):
        new_book = Book(titulo=titulo,autor=autor)
        db.session.add(new_book)
        db.session.commit()

flask_alchemy(Att-MVC)/models/user_model.py
from database import db
from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy import Text 


class User(db.Model):
    __tablename__ = 'users'
    id:Mapped[int] = mapped_column(primary_key=True)
    nome:Mapped[str] = mapped_column("nome", Text, nullable=False )
    email:Mapped[str] = mapped_column("email", Text, nullable=False, unique=True)
     
    def __init__ (self, nome, email):
        self.nome = nome
        self.email = email

    def create_user(nome, email):
        new_user = User(nome=nome,email=email)
        db.session.add(new_user)
        db.session.commit()

flask_alchemy(Att-MVC)/app.py
from flask import Flask 
from database import init_db 
from controllers.user_bp import user_bp 
from controllers.book_bp import book_bp 
from controllers.admin_bp import admin_bp


app = Flask(__name__)
app.config['SECRET_KEY'] =  "SENHA"


init_db(app)

app.register_blueprint(user_bp)
app.register_blueprint(book_bp)
app.register_blueprint(admin_bp)

if __name__ == "__main__":
    app.run(debug=True)
            

flask_alchemy(Att-MVC)/controllers/admin_bp.py
from flask import Blueprint, render_template

from models.user_model import User
from models.book_model import Book

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/')
def index():
    return render_template('index.html')

@admin_bp.route('/listar')
def listar():
    users = User.query.all()  
    books = Book.query.all()  
    return render_template('listar.html', users=users, books=books)

flask_alchemy(Att-MVC)/controllers/book_bp.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, session, make_response

from models.book_model import Book

from database import db

book_bp = Blueprint('book', __name__)


@book_bp.route('/')
def index():
    return render_template('index.html')

@book_bp.route('/create_book', methods=['POST', 'GET'])
def create_book():
    if request.method == 'POST':

        titulo = request.form['titulo']
        autor = request.form['autor']

        Book.create_book(titulo, autor)

        flash("Livro registrado com sucesso!", 'success')
        return redirect(url_for('admin.listar'))

    return render_template('create_book.html')

flask_alchemy(Att-MVC)/controllers/user_bp.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, session, make_response

from models.user_model import User

from database import db

user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def index():
    return render_template('index.html')

@user_bp.route('/create_user', methods=['POST', 'GET'])
def create_user():
    if request.method == 'POST':

        nome = request.form['nome']
        email = request.form['email']

        User.create_user(nome, email)

        flash("Usuário registrado com sucesso!", 'success')
        return redirect(url_for('admin.listar'))

    return render_template('create_user.html')

flask_alchemy(Att-MVC)/database/__init__.py
from flask_sqlalchemy import SQLAlchemy 
from sqlalchemy.orm import DeclarativeBase 

class Base(DeclarativeBase):
    pass

db = SQLAlchemy(model_class=Base)

def init_db(app):
    app.config['SECRET_KEY'] = "Senha"
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///banco.db'
    db.init_app(app)

    with app.app_context():
        db.create_all()



flask_alchemy(Att-MVC)/templates/create_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Livros</title>
</head>
<body>
    <div class="books">

        <form action="{{url_for('book.create_book')}}" method="post">

            <input type="text" name="titulo" placeholder="Titulo" value="{{request.form['titulo']}}">
              
            <input type="text" name="autor" placeholder="Autor">

            <button>Enviar</button>
        </form>
    
    </div>
</body>
</html>

flask_alchemy(Att-MVC)/templates/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Usuários</title>
</head>
<body>
    <div class="users">

        <form action="{{url_for('user.create_user')}}" method="post">

            <input type="text" name="nome" placeholder="Nome">

            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
              
            <button>Enviar</button>
        </form>
    
    </div>
</body>
</html>

flask_alchemy(Att-MVC)/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bem-vindo</title>
</head>
<body>

    <a href="{{url_for('user.create_user')}}">Adicione um usuário</a> <br>

   <a href="{{url_for('book.create_book')}}">Adicione um Livro</a><br>

  <a href="{{url_for('admin.listar')}}">LISTA</a> 
</body>
</html>

flask_alchemy(Att-MVC)/templates/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="users">
        <h4>Usuários</h4>
        <ul>
            {% for user in users %}
            <li>
                <span>Nome:</span> 
                {{user['nome']}}  -  
                

                <span>Email:</span> 
                {{user['email']}} 
                
            </li>
            {% endfor %}
        </ul>
    </div>
    <br>

    <div class="books">
        <h4>Livros</h4>
        <ul>
            {% for book in books %}
            <li>
                <span>Titulo:</span> 
                {{book['titulo']}}  - 

                <span>Autor:</span> 
                {{book['autor']}} 
                
            </li>
            {% endfor %}
        </ul>
    </div>

    <a href="{{url_for('user.create_user')}}"> Adicionar Usuário </a> <br> 

    <a href="{{url_for('book.create_book')}}"> Adicionar Livros</a>

</body>
</html>